version: '3'
services:

  #PHP Service // [azure-container-registry-name].azurecr.io/nginx
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.2-fpm
    container_name: API-Gateway
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: API-Gateway
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./php/pool.d/www2.conf:/usr/local/etc/php-fpm.d/www2.conf      
    networks:
      - app-network
      
  #Nginx Service
  webserver:
    image: nginx:stable
    container_name: API-Gateway-Web-Server
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: API-Gateway-Web-Server
      SERVICE_TAGS: dev
    ports:
      - "8080:80"
      - "4680:443"
      - "9001:9000"      
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
