FROM php:8.2-fpm

#ENV PHP_OPCACHE_VALIDATE_TIMESTAMPS="0" \
#    PHP_OPCACHE_MAX_ACCELERATED_FILES="10000" \
#    PHP_OPCACHE_MEMORY_CONSUMPTION="192" \
#    PHP_OPCACHE_MAX_WASTED_PERCENTAGE="10"


# Set working directory
WORKDIR /var/www

# Install dependencies
USER root
RUN apt-get update && apt-get install -y \
    locales \
    zip \
    curl 
# Install extensions
RUN docker-php-ext-install pdo_mysql mbstring zip exif pcntl


# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Add user for laravel application
RUN groupadd -fg 1000 www
RUN id -u 1000 >/dev/null 2>&1 || useradd -u 1000 -ms /bin/bash -g www www

# Copy existing application directory contents
COPY . /var/www

# Copy existing application directory permissions
COPY --chown=www:www . /var/www

# Change current user to www
USER www

CMD ["php-fpm"]