version: '3'
services:

  #Nginx Service
  webserver:
    image: nginx:stable
    container_name: Nginx-Router
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: Nginx-Router
      SERVICE_TAGS: dev
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/public
      - ./error.log:/var/www/public/error.log
      - ./access.log:/var/www/public/access.log
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      #- ./nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
